---
title: "Projects"
format: 
  html:
    css: "styles.css"
---

### Can Markets Be Predicted?
:::{.project-layout}
Although market returns are not predictable, volatility might be...
[<button>Explore Volatility Analysis</button>](SP8/Can_Markets_Be_Predicted.html)
:::

### Do Equity Research Analyst Recommendations matter?
:::{.project-layout}
What happens to stock prices in response to equity research recommendations?
[<button>Explore Econometric Analysis</button>](SP9/Kent - ECON 381 - Final Term Paper.pdf)
:::

### Implementing Bayesian Statistical Techniques in Genome Wide Association Studies {style="color: #158CBA"}

:::{.project-layout}
Statistical Genetics Project

[<button>Explore Bayesian tools for GWAS</button>](SP6/Digital_Artifact.html)
[<button>Explore Formal Presentation</button>](SP6/Capstone Final Presentation.pdf)
:::

### Forecasting Electricity Usage at Macalester College {style="color: #158CBA"}

:::{.project-layout}
How has the electricity usage at Macalester College changed over the years

[<button>Explore Time Series Analysis</button>](SP7/mini-project.html)
:::

### Modeling Trade Shares of GDP vs Natural Disasters {style="color: #158CBA"}

:::{.project-layout}
How does the number of natural disasters effect the trade share of GDP?

[<button>View disasters VS trade project</button>](SP1/SP_1_Trade:Disasters.qmd)
:::

### Exploring Premier League SPI Ratings {style="color: #158CBA"}

:::{.project-layout}
What types of things impact the Soccer Power Index of a Premier League club?

[<button>Explore Premier League Rankings</button>](SP2/Final_Blog_Post.html)
:::


###  Liberal Arts Education at Macalester College {style="color: #158CBA"}

:::{.project-layout}
What does a liberal arts education look like at Macalester College? What sorts of classes do students take? What kind of departments do they participate in?

[<button>Explore an Education at Macalester College</button>](SP3/Lib_Ed.html)
:::

###  Comparing Fast Food's {style="color: #158CBA"}

:::{.project-layout}
Are there better/healthier caloric fast food restaurants? 

[<button>Explore Fast Foods Restaurants Code</button>](SP4/FinalReport.html)
[<button>Explore Part 1 of analysis</button>](SP4/Final_Phase1.html)
[<button>Explore Part 2 of analysis</button>](SP4/Final_Phase2.html)
:::